var currencies = [
  {"name":"USD", "symbol":"$", "longName":"US Dollar"},
  {"name":"Yen", "symbol":"&yen;", "longName":"Japanese Yen"},
  {"name":"Euro", "symbol":"&euro; ", "longName":"Euro"}
];


var priceBooks = [
  {"id":1, "name":"Japan", "currency":"Yen", "basePrice":309900, "monthlyFee":13000, "monthStartsCounting":2},
  {"id":2, "name":"Korea", "currency":"USD", "basePrice":2500, "monthlyFee":100, "monthStartsCounting":2},
  {"id":3, "name":"Other Asia", "currency":"USD", "basePrice":2900, "monthlyFee":100, "monthStartsCounting":2},
  {"id":4, "name":"India", "currency":"USD", "basePrice":2900, "monthlyFee":100, "monthStartsCounting":2},
  {"id":5, "name":"Germany", "currency":"Euro", "basePrice":980, "monthlyFee":40, "monthStartsCounting":3},
  {"id":6, "name":"Eurozone", "currency":"Euro", "basePrice":1070, "monthlyFee":100, "monthStartsCounting":2},
  {"id":7, "name":"Americas", "currency":"USD", "basePrice":1245, "monthlyFee":65, "monthStartsCounting":2},
  {"id":8, "name":"EMEA", "currency":"USD", "basePrice":1060, "monthlyFee":90, "monthStartsCounting":2},
  {"id":9, "name":"France", "currency": "Euro", "basePrice":1040, "monthlyFee":70, "monthStartsCounting": 2}
];


var countrySource = [
  {"name":"Afghanistan", "pricebook":8},
  {"name":"Aland Islands", "pricebook":8},
  {"name":"Albania", "pricebook":8},
  {"name":"Algeria", "pricebook":8},
  {"name":"American Samoa", "pricebook":7},
  {"name":"Angola", "pricebook":8},
  {"name":"Anguilla", "pricebook":7},
  {"name":"Antigua and Barbuda", "pricebook":7},
  {"name":"Argentina", "pricebook":7},
  {"name":"Armenia", "pricebook":8},
  {"name":"Aruba", "pricebook":7},
  {"name":"Australia", "pricebook":3},
  {"name":"Austria", "pricebook":5},
  {"name":"Azerbaijan", "pricebook":8},
  {"name":"Bahamas", "pricebook":7},
  {"name":"Bahrain", "pricebook":8},
  {"name":"Barbados", "pricebook":7},
  {"name":"Belarus", "pricebook":8},
  {"name":"Belgium", "pricebook":6},
  {"name":"Belize", "pricebook":7},
  {"name":"Benin", "pricebook":8},
  {"name":"Bermuda", "pricebook":7},
  {"name":"Bolivia", "pricebook":7},
  {"name":"Bonaire, Saint Eustatius And Saba", "pricebook":7},
  {"name":"Bosnia And Herzegovina", "pricebook":8},
  {"name":"Botswana", "pricebook":8},
  {"name":"Bouvet Island", "pricebook":8},
  {"name":"Brazil", "pricebook":7},
  {"name":"British Indian Ocean Territory", "pricebook":8},
  {"name":"British Virgin Islands", "pricebook":7},
  {"name":"Brunei", "pricebook":3},
  {"name":"Bulgaria", "pricebook":8},
  {"name":"Burkina Faso", "pricebook":8},
  {"name":"Burundi", "pricebook":8},
  {"name":"Cambodia", "pricebook":3},
  {"name":"Cameroon", "pricebook":8},
  {"name":"Canada", "pricebook":7},
  {"name":"Cape Verde", "pricebook":8},
  {"name":"Cayman Islands", "pricebook":7},
  {"name":"Central African Republic", "pricebook":8},
  {"name":"Chad", "pricebook":8},
  {"name":"Chile", "pricebook":7},
  {"name":"China", "pricebook":2},
  {"name":"Colombia", "pricebook":7},
  {"name":"Comoros", "pricebook":8},
  {"name":"Congo", "pricebook":8},
  {"name":"Congo, The Democratic Republic of the", "pricebook":8},
  {"name":"Cook Islands", "pricebook":7},
  {"name":"Costa Rica", "pricebook":7},
  {"name":"Cote D`Ivoire", "pricebook":8},
  {"name":"Croatia", "pricebook":8},
  {"name":"Cuba", "pricebook":7},
  {"name":"Curacao", "pricebook":7},
  {"name":"Cypress", "pricebook":6},
  {"name":"Czech Republic", "pricebook":8},
  {"name":"Denmark", "pricebook":8},
  {"name":"Dijbouti", "pricebook":8},
  {"name":"Dominica", "pricebook":7},
  {"name":"Dominican Republic", "pricebook":7},
  {"name":"Ecuador", "pricebook":7},
  {"name":"Egypt", "pricebook":8},
  {"name":"El Salvador", "pricebook":7},
  {"name":"Estonia", "pricebook":6},
  {"name":"Equatorial Guinea", "pricebook":8},
  {"name":"Eritrea", "pricebook":8},
  {"name":"Ethiopia", "pricebook":8},
  {"name":"Falkland Islands (Malvinas)", "pricebook":7},
  {"name":"Faroe Islands", "pricebook":8},
  {"name":"Finland", "pricebook":6},
  {"name":"France", "pricebook":9},
  {"name":"French Guiana", "pricebook":7},
  {"name":"French Polynesia", "pricebook":7},
  {"name":"Gabon", "pricebook":8},
  {"name":"Gambia", "pricebook":8},
  {"name":"Georgia", "pricebook":8},
  {"name":"Germany", "pricebook":5},
  {"name":"Ghana", "pricebook":8},
  {"name":"Gibraltar", "pricebook":8},
  {"name":"Greece", "pricebook":6},
  {"name":"Greenland", "pricebook":8},
  {"name":"Grenada", "pricebook":7},
  {"name":"Guadeloupe", "pricebook":7},
  {"name":"Guam", "pricebook":7},
  {"name":"Guatemala", "pricebook":7},
  {"name":"Guernsey", "pricebook":8},
  {"name":"Guinea", "pricebook":8},
  {"name":"Guinea-Bissau", "pricebook":8},
  {"name":"Guyana", "pricebook":7},
  {"name":"Haiti", "pricebook":7},
  {"name":"Honduras", "pricebook":7},
  {"name":"Hong Kong", "pricebook":2},
  {"name":"Hungary", "pricebook":8},
  {"name":"Iceland", "pricebook":8},
  {"name":"India", "pricebook":4},
  {"name":"Indonesia", "pricebook":3},
  {"name":"Iran, Islamic Republic of", "pricebook":8},
  {"name":"Iraq", "pricebook":8},
  {"name":"Ireland", "pricebook":6},
  {"name":"Isle of Man", "pricebook":8},
  {"name":"Israel", "pricebook":8},
  {"name":"Italy", "pricebook":6},
  {"name":"Jamaica", "pricebook":7},
  {"name":"Japan", "pricebook":1},
  {"name":"Jersey", "pricebook":8},
  {"name":"Jordan", "pricebook":8},
  {"name":"Kazakhstan", "pricebook":8},
  {"name":"Kenya", "pricebook":8},
  {"name":"Kiribati", "pricebook":7},
  {"name":"Korea", "pricebook":2},
  {"name":"Kuwait", "pricebook":8},
  {"name":"Kyrgyzstan", "pricebook":8},
  {"name":"Laos", "pricebook":3},
  {"name":"Latvia", "pricebook":6},
  {"name":"Lebanon", "pricebook":8},
  {"name":"Lesotho", "pricebook":8},
  {"name":"Liberia", "pricebook":8},
  {"name":"Libyan Arab Jamahiriya", "pricebook":8},
  {"name":"Lithuania", "pricebook":6},
  {"name":"Luxembourg", "pricebook":6},
  {"name":"Macedonia, The Former Yugoslav Republic of", "pricebook":8},
  {"name":"Madagascar", "pricebook":8},
  {"name":"Malawi", "pricebook":8},
  {"name":"Malaysia", "pricebook":3},
  {"name":"Mali", "pricebook":8},
  {"name":"Malta", "pricebook":6},
  {"name":"Martinique", "pricebook":7},
  {"name":"Mauritania", "pricebook":8},
  {"name":"Mauritius", "pricebook":8},
  {"name":"Mayotte", "pricebook":8},
  {"name":"Mexico", "pricebook":7},
  {"name":"Moldova, Republic of", "pricebook":8},
  {"name":"Mongolia", "pricebook":2},
  {"name":"Montserrat", "pricebook":7},
  {"name":"Morocco", "pricebook":8},
  {"name":"Mozambique", "pricebook":8},
  {"name":"Myanmar", "pricebook":3},
  {"name":"Namibia", "pricebook":8},
  {"name":"Nepal", "pricebook":3},
  {"name":"Netherlands", "pricebook":6},
  {"name":"New Zealand", "pricebook":3},
  {"name":"Nicaragua", "pricebook":7},
  {"name":"Niger", "pricebook":8},
  {"name":"Nigeria", "pricebook":8},
  {"name":"Niue", "pricebook":7},
  {"name":"Norway", "pricebook":8},
  {"name":"Oman", "pricebook":8},
  {"name":"Pakistan", "pricebook":4},
  {"name":"Palestinian Territory, Occupied", "pricebook":8},
  {"name":"Panama", "pricebook":7},
  {"name":"Paraguay", "pricebook":7},
  {"name":"Peru", "pricebook":7},
  {"name":"Philippines", "pricebook":3},
  {"name":"Pitcairn", "pricebook":7},
  {"name":"Poland", "pricebook":8},
  {"name":"Puerto Rico", "pricebook":7},
  {"name":"Portugal", "pricebook":6},
  {"name":"Qatar", "pricebook":8},
  {"name":"Reunion", "pricebook":8},
  {"name":"Romania", "pricebook":8},
  {"name":"Russian Federation", "pricebook":8},
  {"name":"Rwanda", "pricebook":8},
  {"name":"Saint Barthelemy", "pricebook":7},
  {"name":"Saint Helena, Assension and Tristan da Cunha", "pricebook":8},
  {"name":"Saint Kitts and Nevis", "pricebook":7},
  {"name":"Saint Lucia", "pricebook":7},
  {"name":"Saint Martin (French)", "pricebook":7},
  {"name":"Saint Pierre and Miquelon", "pricebook":7},
  {"name":"Saint Vincent and the Grenadines", "pricebook":7},
  {"name":"Samoa", "pricebook":7},
  {"name":"Sao Tome and Principe", "pricebook":8},
  {"name":"Saudi Arabia", "pricebook":8},
  {"name":"Senegal", "pricebook":8},
  {"name":"Serbia", "pricebook":8},
  {"name":"Seychelles", "pricebook":8},
  {"name":"Sierra Leone", "pricebook":8},
  {"name":"Singapore", "pricebook":3},
  {"name":"Sint Maarten (Dutch)", "pricebook":7},
  {"name":"Slovakia", "pricebook":6},
  {"name":"Slovenia", "pricebook":6},
  {"name":"South Georgia and the South Sandwich Islands", "pricebook":7},
  {"name":"Somalia", "pricebook":8},
  {"name":"South Africa", "pricebook":8},
  {"name":"Spain", "pricebook":6},
  {"name":"Sudan", "pricebook":8},
  {"name":"Suriname", "pricebook":7},
  {"name":"Svalbard and Jan Mayen", "pricebook":8},
  {"name":"Swaziland", "pricebook":8},
  {"name":"Sweden", "pricebook":8},
  {"name":"Switzerland", "pricebook":6},
  {"name":"Syrian Arab Republic", "pricebook":8},
  {"name":"Taiwan", "pricebook":2},
  {"name":"Tajikistan", "pricebook":8},
  {"name":"Tanzania, United Republic of", "pricebook":8},
  {"name":"Thailand", "pricebook":3},
  {"name":"Togo", "pricebook":8},
  {"name":"Tokelau", "pricebook":7},
  {"name":"Tonga", "pricebook":8},
  {"name":"Trinidad and Tobago", "pricebook":7},
  {"name":"Tunisia", "pricebook":8},
  {"name":"Turkey", "pricebook":8},
  {"name":"Turkmenistan", "pricebook":8},
  {"name":"Turks and Caicos Islands", "pricebook":7},
  {"name":"Tuvalu", "pricebook":8},
  {"name":"Uganda", "pricebook":8},
  {"name":"Ukraine", "pricebook":8},
  {"name":"U.S. Virgin Islands", "pricebook":7},
  {"name":"United Arab Emirates", "pricebook":8},
  {"name":"United Kingdom", "pricebook":8},
  {"name":"United States Minor Outlying Islands", "pricebook":7},
  {"name":"Uruguay", "pricebook":7},
  {"name":"Uzbekistan", "pricebook":8},
  {"name":"Vanuatu", "pricebook":8},
  {"name":"Vietnam", "pricebook":3},
  {"name":"Venezuela", "pricebook":7},
  {"name":"Western Sahara", "pricebook":8},
  {"name":"Yemen", "pricebook":8},
  {"name":"Zambia", "pricebook":8},
  {"name":"Zimbabwe", "pricebook":8}
];
